export enum JoinGameStep {
    CHOOSEGAMEMODE = 'CHOOSEGAMEMODE',
    BROWSEGAMES = 'BROWSEGAMES',
    ENTERGAMEPIN = 'ENTERGAMEPIN',
    ENTERNICKNAME = 'ENTERNICKNAME',
    LOBBYROOM = 'LOBBYROOM'
}